"""
================================================================================
MODULE 5: Market Regime Detection
================================================================================
PURPOSE:
    Identify latent market regimes (bull/bear/crisis) using unsupervised
    learning. Regime-aware portfolio allocation adapts risk exposure based
    on the current market state.

THEORY:
    Hidden Markov Models (HMMs) assume observed returns are generated by
    an unobservable (hidden) Markov chain of discrete states:

        State: S_t ∈ {1, ..., K}  (e.g., Bull, Bear, Crisis)
        Observation: r_t ~ N(mu_{S_t}, sigma_{S_t})
        Transition: P(S_t | S_{t-1}) = A[S_{t-1}, S_t]

    We implement this using Gaussian Mixture Models (GMM) with temporal
    smoothing as a practical approximation when hmmlearn is unavailable.

    Regime features used:
    - Rolling return (momentum)
    - Rolling volatility (risk level)
    - Rolling skewness (tail behavior)
    - Correlation regime (risk-on vs risk-off)

================================================================================
"""

import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from typing import Dict, Tuple, Optional


class RegimeDetector:
    """
    Market regime detection using Gaussian Mixture Models.

    Identifies distinct market states from return features and
    provides regime-conditional statistics for portfolio allocation.
    """

    REGIME_LABELS = {0: 'Bull', 1: 'Bear', 2: 'Crisis'}

    def __init__(self, n_regimes: int = 3, lookback: int = 63):
        """
        Parameters
        ----------
        n_regimes : int
            Number of latent regimes (default: 3 — Bull/Bear/Crisis).
        lookback : int
            Rolling window for feature computation (default: 63 ≈ 3 months).
        """
        self.n_regimes = n_regimes
        self.lookback = lookback
        self.model = None
        self.scaler = StandardScaler()
        self.regime_stats: Dict = {}

    def _compute_features(self, returns: pd.Series) -> pd.DataFrame:
        """
        Engineer regime-discriminating features from return series.

        Features:
        1. Rolling mean return (momentum signal)
        2. Rolling volatility (risk level)
        3. Rolling skewness (tail asymmetry)
        4. Rolling max drawdown (stress indicator)
        5. Acceleration of volatility (vol-of-vol proxy)
        """
        lb = self.lookback

        features = pd.DataFrame(index=returns.index)

        # 1. Momentum: rolling annualized return
        features['momentum'] = returns.rolling(lb).mean() * 252

        # 2. Volatility: rolling annualized std
        features['volatility'] = returns.rolling(lb).std() * np.sqrt(252)

        # 3. Skewness: rolling skew
        features['skewness'] = returns.rolling(lb).skew()

        # 4. Max drawdown over window
        cumret = (1 + returns).cumprod()
        rolling_max = cumret.rolling(lb).max()
        features['drawdown'] = (cumret - rolling_max) / rolling_max

        # 5. Vol acceleration
        features['vol_accel'] = features['volatility'].diff(21)

        # Drop NaN rows
        features = features.dropna()

        return features

    def fit(self, returns: pd.Series) -> 'RegimeDetector':
        """
        Fit the regime detection model.

        Steps:
        1. Compute features from return series
        2. Standardize features
        3. Fit Gaussian Mixture Model
        4. Label regimes by average return (highest → Bull, etc.)

        Parameters
        ----------
        returns : pd.Series
            Portfolio or market return series.

        Returns
        -------
        self
        """
        features = self._compute_features(returns)
        self.feature_index = features.index

        # Standardize
        X = self.scaler.fit_transform(features.values)

        # Fit GMM
        self.model = GaussianMixture(
            n_components=self.n_regimes,
            covariance_type='full',
            n_init=10,
            max_iter=300,
            random_state=42
        )
        self.model.fit(X)

        # Predict regimes
        raw_labels = self.model.predict(X)
        probs = self.model.predict_proba(X)

        # Relabel by average return: highest mean → regime 0 (Bull)
        regime_returns = {}
        aligned_returns = returns.loc[features.index]
        for k in range(self.n_regimes):
            mask = raw_labels == k
            regime_returns[k] = aligned_returns.iloc[mask].mean()

        sorted_regimes = sorted(regime_returns.keys(),
                               key=lambda k: regime_returns[k], reverse=True)
        label_map = {old: new for new, old in enumerate(sorted_regimes)}

        self.labels = pd.Series(
            [label_map[l] for l in raw_labels],
            index=features.index, name='regime'
        )
        self.probabilities = pd.DataFrame(
            probs[:, sorted_regimes],
            index=features.index,
            columns=[self.REGIME_LABELS[i] for i in range(self.n_regimes)]
        )

        # Compute regime-conditional statistics
        self._compute_regime_stats(aligned_returns)

        return self

    def _compute_regime_stats(self, returns: pd.Series):
        """Compute return statistics conditioned on each regime."""
        for k in range(self.n_regimes):
            mask = self.labels == k
            regime_rets = returns.loc[mask]

            self.regime_stats[self.REGIME_LABELS[k]] = {
                'count': mask.sum(),
                'pct_time': mask.mean() * 100,
                'ann_return': regime_rets.mean() * 252,
                'ann_volatility': regime_rets.std() * np.sqrt(252),
                'sharpe': (regime_rets.mean() / regime_rets.std() * np.sqrt(252)
                          if regime_rets.std() > 0 else 0),
                'skewness': regime_rets.skew(),
                'max_drawdown': self._max_dd(regime_rets),
            }

    @staticmethod
    def _max_dd(returns: pd.Series) -> float:
        cum = (1 + returns).cumprod()
        return ((cum - cum.cummax()) / cum.cummax()).min()

    def predict_current_regime(self) -> Dict:
        """
        Return the current (most recent) regime and probabilities.

        Returns
        -------
        dict
            Current regime label, probabilities, and statistics.
        """
        current_label = self.labels.iloc[-1]
        current_name = self.REGIME_LABELS[current_label]
        current_probs = self.probabilities.iloc[-1].to_dict()

        return {
            'regime': current_name,
            'regime_id': int(current_label),
            'probabilities': current_probs,
            'regime_stats': self.regime_stats.get(current_name, {})
        }

    def get_regime_summary(self) -> pd.DataFrame:
        """Return a summary table of all regime statistics."""
        return pd.DataFrame(self.regime_stats).T

    def get_regime_weights_adjustment(
        self, base_weights: np.ndarray,
        risk_scaling: Dict[str, float] = None
    ) -> np.ndarray:
        """
        Adjust portfolio weights based on current regime.

        In Bear/Crisis regimes, reduce equity exposure and increase
        defensive allocations.

        Parameters
        ----------
        base_weights : np.ndarray
            Base portfolio weights.
        risk_scaling : dict, optional
            Scaling factor per regime for risky assets.
            Default: Bull=1.0, Bear=0.7, Crisis=0.4

        Returns
        -------
        np.ndarray
            Regime-adjusted weights.
        """
        if risk_scaling is None:
            risk_scaling = {'Bull': 1.0, 'Bear': 0.7, 'Crisis': 0.4}

        current = self.predict_current_regime()
        regime = current['regime']
        scale = risk_scaling.get(regime, 1.0)

        # Scale risky assets, put remainder in cash-equivalent
        adjusted = base_weights * scale
        cash_allocation = 1 - adjusted.sum()
        adjusted = adjusted + cash_allocation / len(adjusted)

        # Normalize
        adjusted = adjusted / adjusted.sum()

        return adjusted


# ── Module self-test ──────────────────────────────────────────────────
if __name__ == '__main__':
    from data_generator import MarketDataGenerator

    gen = MarketDataGenerator(seed=42)
    prices, returns, factors = gen.generate_asset_returns(2520)

    # Use market factor as the signal
    market_returns = returns.mean(axis=1)

    detector = RegimeDetector(n_regimes=3, lookback=63)
    detector.fit(market_returns)

    print("=" * 70)
    print("REGIME DETECTION RESULTS")
    print("=" * 70)
    print("\nRegime Summary:")
    print(detector.get_regime_summary().round(4).to_string())
    print("\nCurrent Regime:")
    current = detector.predict_current_regime()
    print(f"  Regime: {current['regime']}")
    print(f"  Probabilities: {current['probabilities']}")
